version: "3"

services:
  ubuntu:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/home/selenium/tests
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
